#' Title Simulate conjoint process of profile selection
#' @description Analysis the conjoint process of profile selection and
#' @param input dataframe with treatment variables generated by generate_sample() and response by simulate_conjoint(), i.e. long conjoint format
#'
#' @return  - est_coef: estimated coefficient
#             - est_se: estimated standard error
#             - true_coef: coefficient from true_coefs[1]
#             - sig: logical, if the est_coef was significant (alpha = 0.05)
#             - in_ci95: logical, if the true_coef was in the CI95
#             - typeS: logical, did the sign of sig. coef match to true?
#             - typeM: ratio of estimated/true, if significant
#              (for typeS and typeM, see Gelman and Carlin, 2014)
#' @export
#'
#' @examples

evaluate.model <- function(input){

  # Debugging for the evaluate.model. The sim_cj is taken from CJpower_simulation.R
  # Simulate conjoint process of profile selection
  # ---------------------------------------------------------------------------
  # Input: data - dataframe with treatment variables generated
  #               by generate_sample() and response by simulate_conjoint(),
  #               i.e. long conjoint format
  #        model_formula - formula for the model to be estimated, by default
  #                        it estimates a gaussian() GLM
  #
  #        true_coefs  - a vector of true parameters to compare the result to
  #                     should be same as coef in simulate_conjoint()
  #
  #
  # Output: vector of results:
  #
  # ---------------------------------------------------------------------------


  #if(is.null(alpha)){alpha <- 0.05}

  num_respondents <- sum(input$inputs$units)
  num_tasks <- length(unique(input$data$task))
  num_attrbs <- sum(str_detect(names(input$data), "var_"))

  if (!"id_grp" %in% names(input$data)){grps_num <- 1} else{
    grps_num <- length(unique(input$data$id_grp))
  }

  if (grps_num == 1){

    model_formula <- as.formula(paste("y ~", paste0("var_", 1:num_attrbs, collapse= " + " )))

    # data <- input$data
    # assign("data", data, envir = .GlobalEnv)

    mod <- glm(model_formula, data = input$data)

    mm_noclust <- marginaleffects::avg_slopes(mod, variables = paste0("var_", 1:num_attrbs),  p_adjust=NULL) |>
      data.frame() |>
      mutate(n_coef = gsub("^(.*?)-.*$", "\\1", contrast)) |>
      mutate(n_coef = gsub("[^0-9.]", "", n_coef)) |>
      mutate(n_coef = as.numeric(n_coef)) |>
      select(-contrast) |>
      select(!starts_with("predicted"))

    mm_robust <- marginaleffects::avg_slopes(mod, variables = paste0("var_", 1:num_attrbs),  p_adjust=NULL, vcov = ~ id) |>
      data.frame() |>
      mutate(n_coef = gsub("^(.*?)-.*$", "\\1", contrast)) |>
      mutate(n_coef = gsub("[^0-9.]", "", n_coef)) |>
      mutate(n_coef = as.numeric(n_coef)) |>
      select(std.error, term, n_coef,conf.low, conf.low, conf.high)  |>
      rename(`std.error.robust` = std.error,
             `conf.low.robust` = conf.low,
             `conf.high.robust` = conf.high
      ) |>
      mutate_at(vars(conf.low.robust, conf.high.robust), ~round(.x, 3))

    mm <- left_join(mm_noclust, mm_robust, by=c("term","n_coef" ))
    #rm(mm_noclust,mm_robust)
    df_loop <- c()

    for (c in 1:length(input$input$true_coef) ) {
      term <- paste0("var_", c)
      for (levels in 1:length(input$input$true_coef[[c]])) {
        n_coef <- levels
        true_coef <-  input$input$true_coef[[c]][[levels]]
        df_loop[[paste(term,n_coef)]] <- data.frame(term, n_coef, true_coef)
      }

    }



    df_bid <- do.call(rbind, df_loop)

    mm <- left_join(mm,df_bid, by=c("term","n_coef" ) )
    rm(mod)
  }else{

    model_formula <- as.formula(paste("y ~", paste0("var_", 1:num_attrbs, "*id_grp" , collapse= " + " )))

    # data <- input$data
    # assign("data", data, envir = .GlobalEnv)
    mod <- glm(model_formula, data = input$data)

    #a <- cjoint::amce(y ~ var_1*id_grp + var_2*id_grp, data=data, cluster=TRUE, respondent.id="id", respondent.varying = "id_grp")
    #summary(a)

    mm_noclust <- marginaleffects::avg_slopes(mod, variables = paste0("var_", 1:num_attrbs), by = "id_grp",  p_adjust=NULL) |>
      data.frame() |>
      mutate(n_coef = gsub("^(.*?)-.*$", "\\1", contrast)) |>
      mutate(n_coef = gsub("[^0-9.]", "", n_coef)) |>
      mutate(n_coef = as.numeric(n_coef)) |>
      select(-contrast) |>
      select(!starts_with("predicted"))

    mm_robust <- marginaleffects::avg_slopes(mod, variables = paste0("var_", 1:num_attrbs), by = "id_grp",   p_adjust=NULL, vcov = ~ id) |>
      data.frame() |>
      mutate(n_coef = gsub("^(.*?)-.*$", "\\1", contrast)) |>
      mutate(n_coef = gsub("[^0-9.]", "", n_coef)) |>
      mutate(n_coef = as.numeric(n_coef)) |>
      select(id_grp, std.error, term, n_coef,conf.low, conf.low, conf.high)  |>
      rename(`std.error.robust` = std.error,
             `conf.low.robust` = conf.low,
             `conf.high.robust` = conf.high
      ) |>
      mutate_at(vars(conf.low.robust, conf.high.robust), ~ round(.x, 3))

    mm <- left_join(mm_noclust, mm_robust, by=c("id_grp","term","n_coef" ))
    #rm(mm_noclust,mm_robust)

    df_loop <- c()
    for (n in names(input$input$true_coef)){
      id_grp <- n
      for (c in 1:length(input$input$true_coef[[n]])) {
        term <- paste0("var_", c)
        for (levels in 1:length(input$input$true_coef[[n]][[c]])) {
          n_coef <- levels
          true_coef <-  input$input$true_coef[[n]][[c]][levels]
          df_loop[[paste(id_grp, term, n_coef)]] <- data.frame(id_grp, term, n_coef, true_coef)
        }

      }

    }

    df_bid <- do.call(rbind, df_loop)

    mm <- left_join(mm,df_bid, by=c("id_grp","term","n_coef" ))
    #rm(mod)

  }


  # Check whether the estimate is in CI95: results to T or F

  # if the estimate is within the CI we say that there is an effect in the population SO that there is difference (effect) when there is a difference (effect)
  # if we get smaller CI (in our case increasing alpha from 0.001 to 0.1 [HIGHER ALPHA]) we DECREASE the chances that the estimate is inside the CI SO that there is difference (effect) when there is a difference (effect)
  # SO this means that we decrease the probability of finding an effect that is there that MEANS LOWER POWER that means higher type II erorr.
  # SO this means that we reduce the chances of saying that there is a difference (effect) when there is not. this means reducing Type I error.
  #HOWEVER WE NEED THE OPPSITITE

  #increasing α (e.g., from .01 to .05 or .10) increases the chances of making a Type I Error (i.e., saying there is a difference when there is not)
  #decreases the chances of making a Type II Error (i.e., saying there is no difference when there is) [SO HIGHER POWER]
  #and decreases the rigor of the test.

  alpha <- 0.05
  z_score <- qnorm(1 - alpha/2)
  # Is significant?

  mm$sig <- ifelse(abs(mm$estimate /  mm$std.error) > z_score, T, F)

  mm$sig_robust <- ifelse(abs(mm$estimate /  mm$std.error.robust) > z_score, T, F)


  # IF sig, is within the CI?
  mm$in_ci95 <- ifelse(mm$sig, ifelse(mm$true_coef < mm$estimate + z_score * mm$std.error &
                                        mm$true_coef > mm$estimate - z_score * mm$std.error,
                                      T, F), F)

  mm$in_ci95_robust <- ifelse(mm$sig_robust,ifelse(mm$true_coef < mm$estimate + z_score * mm$std.error.robust &
                                                     mm$true_coef > mm$estimate -  z_score * mm$std.error.robust,
                                                   T, F), F)

  # confidence intervals
  mm$ci95 <- paste0(round(mm$estimate - (z_score * mm$std.error),3), " -- ", round(mm$estimate + (z_score * mm$std.error),3))
  mm$ci95_robust <- paste0(round(mm$estimate - (z_score * mm$std.error.robust),3), " -- ", round(mm$estimate + (z_score * mm$std.error.robust),3))

  # If significant, Type S

  mm$typeS <- ifelse(mm$sig, ifelse(sign(mm$estimate) == sign(mm$true_coef),
                                    F, T), NA)

  mm$typeS_robust <- ifelse(mm$sig_robust, ifelse(sign(mm$estimate) == sign(mm$true_coef),
                                                  F, T), NA)

  # # If significant, Type M: over/under estimation magnitude
  mm$typeM <- ifelse(mm$sig, mm$estimate / mm$true_coef, NA)

  # - 0.05 / - 0.04
  #
  # - 0.05 / - 0.04

  mm$typeM_robust <- ifelse(mm$sig_robust, mm$estimate / mm$true_coef, NA)

  # inputs to be passed to the result obj
  mm$num_respondents <- num_respondents
  mm$num_attrbs <- num_attrbs
  mm$num_tasks <- num_tasks
  mm$grps_num <- grps_num

  mm <- mm %>% rename(`level` = `n_coef`,
                      `attrb` = `term`
  )


  if (grps_num == 1){  result <-  mm |> select(attrb, level, estimate,
                                               ci95, ci95_robust, true_coef,
                                               num_respondents, num_attrbs,
                                               #num_lvls,
                                               num_tasks,
                                               std.error, std.error.robust,
                                               in_ci95, in_ci95_robust,
                                               sig, sig_robust,
                                               #conf.low.robust, conf.high.robust,
                                               typeS, typeS_robust,
                                               typeM, typeM_robust)}else{



                                                 result <-  mm |> select(id_grp, grps_num,
                                                                         attrb, level, estimate,
                                                                         ci95, ci95_robust, true_coef,
                                                                         num_respondents, num_attrbs,
                                                                         #num_lvls,
                                                                         num_tasks,
                                                                         std.error, std.error.robust,
                                                                         in_ci95, in_ci95_robust,
                                                                         sig, sig_robust,
                                                                         #conf.low.robust, conf.high.robust,
                                                                         typeS, typeS_robust,
                                                                         typeM, typeM_robust)
                                               }



  return(result)
}
